<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-08-19T18:08:31 IST" name="Default suite" finished-at="2024-08-19T18:17:11 IST" duration-ms="520709">
    <groups>
      <group name="cucumber">
        <method signature="AbstractTestNGCucumberTests.runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:TestRunner.TestRunner@23c30a20]" name="runScenario" class="io.cucumber.testng.AbstractTestNGCucumberTests"/>
      </group> <!-- cucumber -->
    </groups>
    <test started-at="2024-08-19T18:08:31 IST" name="Default test" finished-at="2024-08-19T18:17:11 IST" duration-ms="520709">
      <class name="TestRunner.TestRunner">
        <test-method is-config="true" signature="setUpClass(org.testng.ITestContext)[pri:0, instance:TestRunner.TestRunner@23c30a20]" started-at="2024-08-19T18:08:31 IST" name="setUpClass" finished-at="2024-08-19T18:08:31 IST" duration-ms="508" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@25ad25f5]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:TestRunner.TestRunner@23c30a20]" started-at="2024-08-19T18:08:31 IST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2024-08-19T18:17:11 IST" duration-ms="520113" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["Successful Registration with Valid Data"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Banking Automation"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Welcome johndoe] but found [Your account was created successfully. You are now logged in.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Welcome johndoe] but found [Your account was created successfully. You are now logged in.]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at StepDefinitions.StepDefinitionforRegistration.iShouldSeeAConfirmationMessage(StepDefinitionforRegistration.java:75)
at âœ½.I should see a confirmation message "Your account was created successfully. You are now logged in."(file:///C:/Users/chiragsinghp/git/UI_Automation_Frameowrk/src/test/resources/features/Bank_Registration.feature:9)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method is-config="true" signature="tearDownClass()[pri:0, instance:TestRunner.TestRunner@23c30a20]" started-at="2024-08-19T18:17:11 IST" name="tearDownClass" finished-at="2024-08-19T18:17:11 IST" duration-ms="57" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- TestRunner.TestRunner -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
